#! /bin/sh

cd ~/tmp
#rm -rf giac-0.6.1
tar xvfz ~/giac/giac-1.1.3.tar.gz
cd giac-1.1.3/debian
cp -f rules.pari rules
cd ..
#export CXXFLAGS='-g -L/usr/local/lib'
export CXXFLAGS='-DSMARTPTR64 -D_I386_ -O2'
mv debian debiannew
mv debianold debian
mv debiannew debianold
dpkg-buildpackage -rfakeroot
mv debian debiannew
mv debianold debian
mv debiannew debianold
dpkg-buildpackage -us -uc -rfakeroot
