typedef const char * const char4[3];
const char4 aspen_giac_translations [] = {
{"\nEvaluation time: ",0,"\nTemps mis pour l'évaluation: "},
{"\nTry a larger value for tstep",0,"\nEssayez une valeur plus grande pour tstep"},
{"\nTry a larger value for xstep",0,"\nEssayez une valeur plus grande pour xstep"},
{" Computing c ",0," Calcul de c "},
{" Computing inverses mod p of the basis ",0," Calcul des inverses modulo p de la base "},
{" Computing roots mod the basis ",0," Calcul des racines modulo la base "},
{" Early termination",0,0},
{" End large prime hashtables ",0," Fin de la table de hachage des grands premiers "},
{" Error: Bad Argument Type",0," Erreur: Type Argument Incorrect"},
{" Error: Bad Argument Value",0," Erreur: Valeur Argument Incorrecte"},
{" Error: Invalid dimension",0," Erreur: Dimension incorrecte"},
{" Init large prime hashtables ",0," Initialise la table de hachage des grands premiers "},
{" Pollard-rho failure, ntries ",0," Echec de la méthode de Pollard-rho, nombre d'essais "},
{" Pollard-rho try ",0," Essai de la méthode de Pollard-rho "},
{" Polynomial a,b,M=",0,"Polynôme a,b,M="},
{" Sieve large remainder:",0," Sieve large remainder:"},
{" already additional",0," déjà rajouté"},
{" already assigned. Trying ",0," déjà affecté. Essayer"},
{" and ",0," et "},
{" and <=",0," et <="},
{" and is estimated to be less than 10^-",0," et est estimee etre plus petite que 10^-"},
{" as generator for Galois field ",0," comme générateur du corps de Galois "},
{" at parameters values ",0,0},
{" by ",0," par "},
{" by 0",0," par 0"},
{" compiling ",0," lors de la compilation "},
{" declared as global variable(s). If symbolic variables are required, declare them as local and run purge\n",0,"declare(s) comme variable(s) globale(s). Si vous avez besoin de variables symboliques, declarez les en local et faites purge\n"},
{" dividing by determinant",0," en divisant par le déterminant"},
{" end dividing by determinant",0," fin de division par le déterminant"},
{" end relations ",0," fin des relations "},
{" end removing additional primes",0," Fin d'enlèvement des premiers additionnels"},
{" end reset, nbits ",0," end reset, nbits "},
{" equation ",0,"équation"},
{" error, try debug(",0," erreur, essayez debug("},
{" fixed begin at ",0," fixé le début à "},
{" for definite integration in [",0," pour calculer l'intégrale definie dans ["},
{" function not supported, doing like if it was defined",0," fonction non prevue, on fait comme si elle etait definie"},
{" in ",0," dans "},
{" initial value for M= ",0," valeur initiale pour M= "},
{" instead ",0," au lieu de "},
{" instead, even if the argument should be of type function",0,"a la place, meme si l'argument doit etre de type fonction "},
{" instead.",0," au lieu de "},
{" instruction #",0," instruction #"},
{" integer solutions for ",0," solution entière pour "},
{" is a reserved word, sto not allowed:",0," est un mot réservé, sto ne peut être utilisé"},
{" is irreducible but not primitive. You could use ",0," irreductible mais non primitif. Vous devez utiliser "},
{" is locked by thread (in sto) ",0," est bloqué par la tâche (dans sto) "},
{" is not analytic",0," n'est pas analitique"},
{" is not rational w.r.t. ",0," n'est pas un rationel relativement à "},
{" is not rationnal w.r.t. ",0," n'est pas un rationnel relativement à "},
{" is on the unit circle, using residues",0," est sur le cercle unité, en utilisant les résidus"},
{" multiargs not implemented",0," Plusieurs args: à implementer"},
{" not allowed!",0," non autorisé!"},
{" of antiderivative",0," de la primitive"},
{" or "," or "," ou "},
{" or chisquare_icdf(",0," ou chisquare_icdf("},
{" removing additional primes",0," enlève les premiers additionnels"},
{" reset",0," reset"},
{" samples Chi2 test result ",0," echantillons, resultat du test du Chi2 "},
{" should be of type _VECT (unary.cc)",0," devrait être de type _VECT (unary.cc)"},
{" should be purged",0," doit être purgée"},
{" sieve basis OK, size ",0," sieve basis OK, size "},
{" sieve begin ",0," sieve begin "},
{" sieve current basis size ",0," sieve current basis size "},
{" sieve done: used ",0," sieve done: used "},
{" sieve on ",0," sieve on "},
{" sieved : ",0," sieved : "},
{" solving equation ",0," en résolvant l'équation"},
{" to integer ",0," vers entier "},
{" true relation ",0," relation vraie "},
{" using ",0," en utilisant "},
{" was discarded and replaced randomly by ",0," n'a pas ete utilisee, elle a ete remplacee au hasard par "},
{" where ",0," où "},
{"%gen\nReduce column %gen with pivot %gen at row %gen",0,"%gen\nReduction colonne %gen avec pivot %gen a la ligne %gen"},
{"%gen critical point (0 as eigenvalue) %gen",0,"point critique %gen (0 est valeur propre) %gen"},
{"%gen critical point (unknown type)",0,"point critique %gen (type inconnu)"},
{"%gen is a critical point (unknown type)",0,"%gen est un point critique de type inconnu"},
{"%gen is a local maximum",0,"%gen est un maximum local"},
{"%gen is a local maximum %gen",0,"%gen est un maximum local %gen"},
{"%gen is a local minimum",0,"%gen est un minimum local"},
{"%gen is a local minimum %gen",0,"%gen est un minimum local %gen"},
{"%gen is a saddle point (2 eigenvalues with opposite sign) %gen",0,"%gen est un point col (2 valeurs propres de signe oppose) %gen"},
{"%gen is an inflection point",0,0},
{"(Mac OS) Large number, you can try pari(); pari_factor(",0,0},
{"(a-b) is not 0.\nTherefore a==b may return false even if a and b are mathematically equal,\nif they have different internal representations.\nYou can explicitly call a simplification function like simplify(a-b)==0 to avoid this.",0,"n'est pas 0.\nDonc a==b peut retourner faux meme si a et b sont mathematiquement egaux,\nsi ils ont une representation interne differente.\nVous pouvez appeler explicitement une fonction de simplification comme simplify(a-b)==0 pour eviter ce probleme"},
{"(auxiliary polynomial variable for addition representation ",0,"(variable polynomiale auxiliaire pour représentation additive "},
{"(null hyp. mu1=mu2 rejected with less than alpha probability error)",0,"(hyp. nulle mu1=mu2 rejetee avec une probabilite d'erreur inferieure a alpha"},
{") exceeded or non unidirectional series",0,") dépassement ou développement en séries bidirectionnel"},
{") invalid, works only for integers or polynomials depending on ",0,") invalide, marche juste pour les entiers ou polynômes dependant de "},
{"*** TEST RESULT ",0,"*** RESULTAT DU TEST "},
{"*Pcumul+",0,"*Pcumul+"},
{",\nreject adequation if superior to chisquare_icdf(",0,",\nOn rejette l'adequation si superieur a chisquare_icdf("},
{", Chi2 test result ",0,", resultat du test du Chi2 "},
{", Estimated total P=",0,", estimation P total="},
{", a substitution variable should perhaps be purged.",0,", une variable de substitution doit probablement être purgée"},
{", answer may be wrong.\nIf you are computing an integral with exact boundaries, replace by approx. boundaries",0,", reponse peut-etre fausse.\nSi vous calculez une integrale definie, utilisez des bornes approchees"},
{", confidence level: ",0,", niveau de confiance : "},
{", degrees of freedom ",0,", degres de liberte "},
{", p-value: ",0,0},
{", population mean mu2=",0,", moyenne de la population mu2="},
{", switching to approx. solutions",0,", changement pour des solutions approx."},
{",1-alpha) if alpha!=5%",0,",1-alpha) si alpha!=5%"},
{". Use proba_epsilon:=0 to certify (this takes more time).",0,". Utilisez proba_epsilon:=0 pour un resultat certifie, attention cela prend plus de temps."},
{". You should use ",0,". Vous devriez utiliser "},
{"// Error(s)\n",0,"// Erreurs(s)\n"},
{"// Invalid program",0,0},
{"// Parsing ",0,"// Interprète "},
{"// Success\n",0,"// Succès\n"},
{"// Warning, assignation is :=, check the lines below:\n",0,0},
{"// Warning, duplicate argument name: ",0,"// Attention, deux fois le meme nom d'argument"},
{"// Warning: ",0,"// Attention: "},
{"1st arg=open result, then other args",0,"1er arg=résultat de open, ensuite autres args"},
{"2 parallel lines",0,"Droites parallèles"},
{"2 parallel plans",0,"2 Plans parallèles"},
{"2 plans intersecting at ",0,"2 plans se coupant selon "},
{"2 secant lines at (",0,"2 droites sécantes en ("},
{"2-d instruction",0,"Instruction 2-d"},
{"2-d line/sphere",0,"droite 2-d/sphere"},
{"2-d point expected",0,"Attend un point du plan"},
{"2-fold hyperboloid of center ",0,"Hyperboloïde à 2 nappes de centre "},
{"2nd arg",0,"2eme arg"},
{"2nd arg must be a free variable",0,"2eme argument doit être une variable non affectée"},
{"3 or 4 arguments expected",0,"Nécessite 3 or 4 arguments"},
{"3 points expected",0,"Nécessite 3 points"},
{"3-d enveloppe not implemented",0,"enveloppe: non implémentée en 3-d"},
{"3-d instruction",0,"Instruction 3-d"},
{"3-d line/2-d circle",0,"droite 3-d/cercle 2-d"},
{"3rd party data",0,"Donnée tierce"},
{": recursive definition",0,": définition récursive"},
{": recursive definition (in sto) ",0,": définition récursive (dans sto) "},
{"=0: no solution found",0,"=0: Pas de solution trouvée"},
{"===== Critical points for %gen =====",0,"===== Points critiques de %gen ====="},
{"===== Derive %gen with respect to %gen =====",0,"===== Derivee de %gen par rapport a %gen ====="},
{"===== Step/step primitive of %gen with respect to %gen =====",0,"===== Integration pas a pas pour %gen par rapport a %gen ====="},
{"====================\nFunction plot %gen, variable %gen",0,"====================\nGraphe de fonction %gen, variable %gen"},
{"====================\nParametric plot (%gen,%gen), variable %gen",0,0},
{"Algebraic extensions not allowed in a rootof",0,"Extension algébrique non autorisée dans un rootof"},
{"Archiving ",0,"Archivage "},
{"Args must be multivariate polynomials",0,"Arguments doivent être des polynômes à plusieurs variables"},
{"Argument must be a vector of even size",0,"Argument doit etre un vecteur de taille paire"},
{"Argument should be of type ",0,"Argument devrait être de type "},
{"Array too large",0,"Tableau trop grand"},
{"Asm programs not implemented",0,"Programme assembleur non implementés"},
{"Assigning variables ",0,"Assigne les variables "},
{"Assuming false condition ",0,"En supposant la condition fausse "},
{"Assuming true condition ",0,"En supposant la condition vraie "},
{"Assuming you want to run polygonscatterplot",0,"On suppose que vous vouliez taper polygonscatterplot"},
{"Asymptote %gen",0,"Asymptote %gen"},
{"Asymptote at %gen: %gen",0,"Asymptote en %gen: %gen"},
{"Auto-declared local variables : ",0," déclarée(s) automatiquement comme variable(s) locale(s)"},
{"Back substitution %gen->%gen in %gen",0,"Substitution %gen->%gen dans %gen"},
{"Bad Argument Type",0,"Type Argument Incorrect"},
{"Bad Argument Value",0,"Valeur Argument Incorrecte"},
{"Bad alternative hypothesis, should be '>', '<' or '!='",0,"Hypothese alternative inconnue, devrait etre '>', '<' or '!='"},
{"Bad branch, questionnable accuracy",0,"Branche incorrecte, précision discutable"},
{"Bad cell",0,"cellule invalide"},
{"Bad characteristic: ",0,"Caractéristique incorrecte: "},
{"Bad conversion basis",0,"Base de conversion invalide"},
{"Bad dimension for qb or rb or b or degrees",0,"Dimension incorrecte pour qb ou rb ou b ou degrés"},
{"Bad equal in",0,"Egal incorrect dans"},
{"Bad index",0,"Index invalide"},
{"Bad index (in sto) ",0,"Index incorrect (dans sto) "},
{"Bad indexes in recurrence",0,"Indices incorrects dans la récurrence"},
{"Bad iteration",0,"Itération incorrecte"},
{"Bad mod value",0,"Valeur du modulo invalide"},
{"Bad precision, using 1e-12 instead of ",0,"Mauvaise précision en utilisant 1e-12 à la place de "},
{"Bad rootof",0,"rootof invalide"},
{"Bad rootof (in sto)",0,"rootof invalide dans sto"},
{"Bad state",0,"Etat invalide"},
{"Bad step",0,"Discretisation incorrecte (step)"},
{"Bad var ",0,"Mauvaise var "},
{"Bad when ",0,"when incorrect "},
{"Bessel",0,"Bessel"},
{"Bessel not implemented",0,"Bessel non implementee"},
{"Binomial: estimating n and p from data ",0,"Loi binomiale: estimation de n et p par les donnees"},
{"Boundaries not integer",0,"Les limites doivent être des entiers"},
{"Boundary conditions for parametric curve not implemented",0,"Conditions aux bords pour les courbes paramétrées non implementés"},
{"Bug in conique reducing ",0,"Bug dans conique en réduisant "},
{"Bug in conique, equation ",0,"Bug dans conique, équation "},
{"Bug in quadrique reducing ",0,"Bug dans la réduction de quadrique "},
{"Bug in quadrique, equation ",0,"Bug dans l'équation de quadrique "},
{"Bug!",0,"Bug!"},
{"Can not expand remainder of integrand",0,"Impossible de développer le reste de l'intégrant"},
{"Can't check irreducibility extracting rootof",0,"Impossible de tester l'irréductibilité en extrayant rootof"},
{"Can't check sign ",0,"Impossible de déterminer le signe "},
{"Can't find length of non tokenized programs",0,"Ne peut trouver la longueur d'un programme non tokenisé"},
{"Can't isolate",0,"Impossible d'isoler"},
{"Cancel thread ",0,"Annuler la tâche "},
{"Cas_setup ",0,"Configuration du Cas "},
{"Checking exact value of integral with numeric approximation",0,"On verifie la valeur exacte de l'integrale avec une approximation numerique"},
{"Circle centers are identical",0,"Centres des cercles sont identiques"},
{"Click reads ",0,"Cliquer reads "},
{"Collinear points",0,"Points colinéaires"},
{"Cone of center ",0,"Cône de centre "},
{"Converting ",0,"Conversion "},
{"Correlation ",0,"Correlation"},
{"Correlation for 5 first years to estimate initial cumulative : ",0,"Corrélation des 5 premières années vers estimation cumulée initiale : "},
{"Could not open file",0,"Impossible d'ouvrir le fichier"},
{"Cst part must be hypergeometric",0,"Le second membre doit etre hypergeometrique"},
{"Cst part must be of type a^n*P(n)",0,"Le second membre doit etre de la forme a^n*P(n) "},
{"Data mean mu1=",0,"Moyenne donnees mu1="},
{"Data should be a class number between 0 and ",0,"La donnee devrait etre un numero de classe entre 0 et"},
{"Data_var_tag not implemented",0,"Data_var_tag non implementé"},
{"Derivative of %gen apply linearity: (u+v+...)'=u'+v'+...",0,"Derivee de %gen on applique la linearite (u+v+...)'=u'+v'+..."},
{"Derivative of %gen with respect to %gen is %gen\nSolving %gen with respect to %gen answer %gen",0,"Derivee de %gen par rapport a %gen est %gen\nResolution de %gen par rapport a %gen resultat %gen"},
{"Derivative of %gen, apply product rule: (u*v*...)'=u'*v*...+u*v'*...+...",0,"Derivee de %gen, un produit: (u*v*...)'=u'*v*...+u*v'*...+..."},
{"Derivative of %gen/%gen, a quotient: (u/v)'=(u'*v-u*v')/v^2",0,"Derivee de %gen/%gen, un quotient: (u/v)'=(u'*v-u*v')/v^2"},
{"Derivative of a composition: (%gen)'=(%gen)'*f'(%gen) where f=%gen",0,"Derivee d'une composee: (%gen)'=(%gen)'*f'(%gen) avec f=%gen"},
{"Derivative of a power: (%gen)'=%gen*(%gen)'*ln(%gen)+(%gen)*(%gen)'*%gen",0,"Derivee of d'une puissance: (%gen)'=%gen*(%gen)'*ln(%gen)+(%gen)*(%gen)'*%gen"},
{"Derivative of a power: (%gen)'=(%gen)*(%gen)'*%gen",0,"Derivee d'une puissance: (%gen)'=(%gen)*(%gen)'*%gen "},
{"Derivative of elementary function %gen is %gen",0,0},
{"Derivative of inv(u)=-u'/u^2 with u=%gen",0,"Derivee de inv(u)=-u'/u^2 avec u=%gen"},
{"Derivative of rootof currently not handled",0,"Derivée de rootof non implementée"},
{"Discontinuities at zeroes of ",0,"Discontinuités aux zeros de "},
{"Distance curve/curve not implemented",0,"Distance courbe/courbe non implémentée"},
{"Division by 0",0,"Division par 0"},
{"Division of ",0," Division de "},
{"Domain %gen",0,"Domaine %gen"},
{"Each element must be a face (vector of 3/4 points)",0,"Chaque élément doit être une face (vecteur de 3 ou 4 points)"},
{"Ellipsis of center (",0,"Ellipse de centre ("},
{"Ellipsis reduced to (",0,"Ellipse réduite à ("},
{"Ellipsoid of center ",0,"Ellipsoïde de centre "},
{"Elliptic cylinder around ",0,"Cylindre elliptique d'axe "},
{"Elliptic paraboloid of center ",0,"Paraboloïde elliptique de centre "},
{"Empty ellipsis",0,"Ellipse vide"},
{"Empty ellipsoid",0,"Ellipsoïde vide"},
{"Empty parabola",0,"Parabole vide"},
{"End interactive_plotode",0,"Arrêt de interactive_odeplot"},
{"End of stream",0,"Fin de flux"},
{"End reduction %gen",0,"Fin de reduction %gen "},
{"End structure ",0,"Fin de structure "},
{"End_tag/End_of_segment",0,"End_tag/End_of_segment"},
{"Equation 0 = ",0,"Équation 0 = "},
{"Error in PARI subsystem",0,"Erreur dans PARI"},
{"Error index.cc index_gcd",0,0},
{"Error opening audio device.",0,"Erreur d'ouverture audio"},
{"Error printasmaple_lib",0,0},
{"Error solving equations. Check that your variables are purged",0,"Impossible de resoudre les equations. Verifiez que vos variables sont libres (purge)"},
{"Error while checking exact value with approximate value, returning both!",0,"Erreur, la valeur numerique ne correspond pas a la valeur exacte de l'integrale, on renvoie les deux!"},
{"Error writing ",0,"Erreur d'écriture "},
{"Error: Bad Argument Type",0," Erreur: Type Argument Incorrect"},
{"Error: Bad Argument Value",0," Erreur: Valeur Argument Incorrecte"},
{"Error: Division of ",0,"Erreur: Division de "},
{"Error: Invalid dimension",0," Erreur: Dimension invalide"},
{"Error: Invalid series expansion: ",0,"Erreur: Développement en séries incorrect: "},
{"Error: Max order (",0,"Erreur: Ordre maximal ("},
{"Error: Too few arguments: ",0,"Erreur: Pas assez d'arguments: "},
{"Error: Too many arguments: ",0,"Erreur: Trop d'arguments: "},
{"Error: Unable to check sign: ",0,"Erreur: Impossible de déterminer le signe: "},
{"Error: calculation size limit exceeded",0,"Erreur: taille limite de calcul dépassée"},
{"Estimated mean from sample(s)",0,"Moyenne estimee en utilisant le(s) echantillon(s)"},
{"Estimated sigma from sample(s)",0,"Ecart-type estime depuis le(s) echantillon(s)"},
{"Evaluation time: ",0,"Temps mis pour l'évaluation: "},
{"Even function %gen, odd function %gen. Reflection Ox",0,"Fonction paire %gen, fonction impaire %gen. Symetrie Ox"},
{"Even function %gen. Reflection Oy",0,"Fonction paire %gen. Symetrie Oy"},
{"Even functions.",0,"Fonction paires."},
{"Exchange row %gen and row %gen",0,"Echange ligne %gen et ligne %gen"},
{"Expecting a square matrix",0,"Nessécite une matrice carrée"},
{"Expecting an expression, not a function",0,"Attend une expression, pas une fonction"},
{"Expecting characteristic p, integer m",0,"Attendu la caractéristique p, entier m"},
{"Expecting file name to convert",0,"Necéssite un nom de fichier pour convert"},
{"Expecting modular coeff",0,"Coefficient modulaire attendu"},
{"Exponent must be >=2: ",0,"Exposant doit être >=2: "},
{"Factor: Only one algebraic extension allowed",0,"Factor: une seule extension algébrique possible"},
{"Field too large",0,"Cardinal du corps trop grand"},
{"File","File","Fich"},
{"File not found or unrecognized image file format",0,"Fichier non trouvé ou format d'image non reconnu"},
{"File not found or unrecognized wav file format",0,"Fichier non trouvé ou format wav non reconnu"},
{"First M ",0,"Premier M "},
{"First arg of translation should not be a point",0,"Le premier arg de translation doit être un point"},
{"Float too large",0,"Flottant trop grand"},
{"Floor definite integration: can only handle linear < or > condition",0,"Intégration définie avec floor: ne peut traiter que des inéquations linéaires"},
{"Floor definite integration: unable to handle infinite boundaries",0,0},
{"For must have 4 args",0,"for doit avoir 4 args"},
{"For: Unable to check test",0,"For: impossible de faire le test"},
{"Function not defined",0,"Fonction non définie"},
{"GCD not successfull",0,"PGCD: echec"},
{"GF inv internal bug",0,"GF inv bug interne"},
{"GF is used for non-prime finite field. Use % or mod for prime fields, e.g. 1 % ",0,"GF est utilisé pour les corps finis non premier. Utiliser % ou mod pour les corps premiers, par ex 1"},
{"GF polyfactor",0,"GF polyfactor"},
{"Gdb_var_tag not implemented",0,"Gdb_var_tag non implementé"},
{"Gen Destructor",0,"Gen Destructor"},
{"Gen Operator =",0,0},
{"Give a filename, e.g. ",0,"Donnez un nom de fichier par exemple "},
{"Give a name to the procedure, e.g. test",0,"Donner un nom à la procédure, par ex essai"},
{"Give a name to thr procedure, e.g. ",0,"Donner un nom à la procédure, par ex "},
{"Gnuplot write error",0,0},
{"Guessing data is a list of values, adequation to uniform discret distribution between ",0,"On suppose que les donnees sont des valeurs, adequation a la ditribution uniforme discrete entre "},
{"Guessing data is the list of number of elements in each class, adequation to uniform distribution",0,"On suppose que les donnees dont des effectifs de classes, adequation a la distribution uniforme"},
{"Guessing initial production requires more than 20 samples",0,"Il faut plus de 20 données pour deviner la production initiale"},
{"Hence derivative of %gen by linearity is %gen",0,"Donc la derivee de %gen par linearite est %gen"},
{"Hence derivative of %gen by product rule is %gen",0,"Donc la derivee de %gen par la regle du produit est %gen"},
{"Hence primitive of %gen with respect to %gen is %gen",0,"Donc la primitive de %gen par rapport a %gen est %gen"},
{"Hessian at %gen : %gen",0,"Hessienne en %gen : %gen"},
{"Homogeneous differential equation",0,0},
{"Horizontal asymptote %gen",0,0},
{"Horizontal asymptote at %gen : %gen",0,"Asymptote horizontale en %gen : %gen"},
{"Horizontal parabolic asymptote at %gen",0,"Branche parabolique horizontale en %gen"},
{"Hyperbola of center (",0,"Hyperbole de centre ("},
{"Hyperbolic cylinder around ",0,"Cylindre hyperbolique d'axe "},
{"Hyperbolic paraboloid of center ",0,"Paraboloïde hyperbolique de centre "},
{"Hypersurface w/o equation",0,"Hypersurface sans équation"},
{"Hypersurface w/o equation not implemented",0,"Hypersurface sans équation: non implémentée"},
{"Ifte must have 3 args",0,"Ifte doit avoir 3 args"},
{"Ifte: Unable to check test",0,"Ifte: impossible de faire le test"},
{"Impliciplot: temporarily swtiching to real mode",0,"Impliciplot: passage temporaire en mode réel"},
{"Implicit multiplication does not work with complex numbers.",0,"La multiplication implicite n'est pas supportee avec des nombres complexes"},
{"Implicitplot ",0,"Implicitplot "},
{"Incompatible characteristics",0,"Caractéristiques incompatibles"},
{"Incompatible coeff type",0,"Type de coefficient incompatible"},
{"Incompatible system",0,"Système incompatible"},
{"Incompatible units",0,"Unités incompatibles"},
{"Incomplete",0,"Incomplète"},
{"Increment",0,"Incrémenter"},
{"Index outside of range (in sto) ",0,"Index en dehors de l'intervalle (dans sto) "},
{"Inequation inside inequation not implemented ",0,"Inéquation dans une inéquation est non implementée"},
{"Inequation is constant with respect to ",0,"Inéquation est constante par rapport à"},
{"Infinite number of critical points. Try with optional argument ",0,"Infinite de points critiques. Essayez avec des options."},
{"Infinity or undefined limit at bounds.\nUsing middle point Romberg method",0,"Limite aux bornes est infinie ou indéfinie.\nOn utilise la méthode de Romberg avec le point milieu"},
{"Initial cumulative estimated to ",0,"Estimation cumulée initiale de "},
{"Inputform reads ",0,0},
{"Instruction debut_enregistrement not found",0,"Instruction debut_enregistrement non trouvée"},
{"Integer argument >= 2",0,"Argument entier >= 2"},
{"Integer matrix expected",0,"Necéssite une matrice à coeffs entiers"},
{"Integer too large",0,"Entier trop grand"},
{"Integral in limit not implemented yet",0,"Intégrale dans une limite : non implementé"},
{"Integral must be definite",0,"Intégrale doit être définie"},
{"Integrate %gen, a linear expression u=%gen to a constant power n=%gen,\nIf n=-1 then ln(u)/a else u^(n+1)/((n+1)*%gen)",0,"Integration de %gen, expression lineaire u=%gen a une puissance constante n=%gen,\nSi n=-1 alors ln(u)/a sinon u^(n+1)/((n+1)*%gen)"},
{"Integrate %gen, a linear expression u=%gen to a constant power n=1/%gen,\nIf n=-1 then ln(u)/a else u^(n+1)/((n+1)*%gen)",0,"Integration de %gen, une expression lineaire u=%gen a la puissance n=1/%gem,\nSi n=-1 alors ln(u)/a sinon u^(n+1)/((n+1)*%gen)"},
{"Integrate %gen, change of variable %gen->%gen, new integral %gen",0,"Integration de %gen, changement de variables %gen->%gen, nouvelle integrale %gen"},
{"Integrate %gen, no heuristic found, running Risch algorithm",0,"Integration de %gen, pas d'heuristique trouvee, on lance l'algorithme de Risch"},
{"Integrate %gen: function %gen applied to a linear expression u=%gen, result %gen",0,"Integration de %gen: fonction %gen appliquee a une expression lineaire u=%gen, resultat %gen"},
{"Integrate linearizable expression %gen -> %gen",0,"Integration d'une expression linearisable %gen -> %gen"},
{"Integrate rational fraction %gen",0,0},
{"Integrate rational fraction %gen, change of variable %gen",0,0},
{"Integrate rational fraction of exponential %gen by %gen change of variable, leading to integral of %gen",0,"Integration d'une fraction rationnelle d'exponentielle %gen par changement de variable %gen, donne l'integrale de %gen"},
{"Integrate rational fraction of trigonometric %gen by %gen change of variable, leading to integral of %gen",0,"Integrale de fraction rationnelle trigonometrique %gen par changement de variable %gen, donne l'integrale de %gen"},
{"Integrate rational fraction with denominator %gen=0\nroots are deduced from nth-roots of unity",0,"Integration d'une fraction rationnelle avec denominateur %gen=0\nles racines sont deduites des racines n-iemes de l'unite"},
{"Integrate rational fraction with denominator a cyclotomic polynomial, roots are primitive roots of %gen=0",0,"Integration d'une fraction rationnelle dont le denominateur est cyclotomique, les racines sont les racines primitives de %gen=0"},
{"Integrate trigonometric linearizable expression %gen -> %gen",0,"Integration d'une expression trigonometrique linearisable %gen -> %gen"},
{"Integration of %gen by part of u*v' where u=1 and v=%gen'",0,"Integration de %gen par parties u*v' avec u=1 et v=%gen'"},
{"Integration of %gen: by part, u*v'=%gen*(%gen)'",0,"Integration de %gen par partie, u*v'=%gen*(%gen)'"},
{"Integration of %gen: f(u)*u' where f=%gen->%gen and u=%gen",0,"Integration de %gen: f(u)*u' avec f=%gen->%gen et u=%gen"},
{"Integration of a rational fraction with denominator %gen\nroots are obtained by solving the 2nd order equation %gen=0 then extracting nth-roots",0,"Integration d'une fraction rationnelle avec denominateur %gen\nLes racines sont obtenues en resolvant l'equation du 2eme degre %gen=0 puis extraction de racines n-iemes"},
{"Integration variable and limit variable are the same",0,"La variable d'intégration et de limite doivent etre distinctes"},
{"Integration variable must be != from series expansion variable",0,"Variable d'intégration doit être différente de la variable de développement en séries"},
{"Internal sincos token",0,"Token sincos interne"},
{"Interrupted ",0,"Interrompu "},
{"Invalid _EXT in replace_ext",0,0},
{"Invalid argument name ",0,"Nom d'argument invalide"},
{"Invalid class size (replaced by 1) ",0,"Dim de la classe invalide (replacé par 1) "},
{"Invalid confidence level",0,"Niveau de confiance invalide"},
{"Invalid dimension",0,"Dimension invalide"},
{"Invalid giac gen -> CoCoA ZZ conversion",0,"Conversion invalide de giac gen vers CoCoA ZZ"},
{"Invalid loop index (hint: i=sqrt(-1)!)",0,"Index de boucle invalide (indication: i=sqrt(-1)!)"},
{"Invalid map",0,"map invalide"},
{"Invalid median",0,"Mediane invalide"},
{"Invalid null step",0,"step nul est incorrect"},
{"Invalid or typed variable(s) name(s) were replaced by creating special identifiers, check ",0,"Des variables avec type specifie ou de nom invalide ont ete remplacee par un identificateur modifie, verifiez "},
{"Invalid sample",0,"Echantillon incorrect"},
{"Invalid series expansion: ",0,"Développement en séries incorrect: "},
{"Invalid sound data",0,"Donnee son invalide"},
{"Invalid sound parameters",0,"Parametres du son invalides"},
{"Invalid step value",0,"Valeur de step incorrecte"},
{"Invalid unit exponent",0,"Exposant invalide pour une unité"},
{"Invalid variable ",0,"Variable invalide "},
{"Invalid |",0,"| incorrect"},
{"Inverse z-transform of non rational functions not implemented or unable to fully factor rational function",0,"Transformée en z inverse d'une fonction non rationnelle non implementée ou impossible de factoriser complètement une fonction rationnelle "},
{"Iquo",0,"iquo"},
{"L%gen <- (%gen)*L%gen-(%gen)*L%gen on %gen",0,0},
{"LAPACK LU error",0,"LAPACK LU erreur"},
{"LAPACK error ",0,"LAPACK erreur "},
{"LAPACK not available",0,"LAPACK non disponible"},
{"Lapack conversion error",0,"Lapack  erreur de conversion"},
{"Limit probably undefined, algorithm unable to handle ",0,0},
{"Line ",0,"Droite "},
{"Lines must intersect",0,"Les droites doivent être sécantes"},
{"Local must have 2 args",0,"Local doit avoir 2 args"},
{"Local var protected ",0,"Variable locale protégée "},
{"Locus on an unknown parametric curve type",0,"Lieu par rapport à un type de courbe paramétrique inconnu"},
{"Longfloat library not available",0,"Librairie de flottants multiprécision non présente"},
{"Low accuracy",0,"Faible précision"},
{"Low accuracy for Schur row ",0,"Precision basse pour Schur, ligne "},
{"Low accuracy or not diagonalizable at some eigenvalue. Try jordan if the matrix is exact.",0,"Precision faible ou matrice non diagonalisable. Essayez jordan si la matrice est exacte."},
{"Making implicit assumption for sqrt argument ",0,"On effectue une hypothese implicite pour l'argument de sqrt "},
{"Maple/Mupad/TI For: unable to convert",0,0},
{"MathMl convert ",0,"Conversion MathMl"},
{"Max order (",0,"Ordre maximal ("},
{"Minimal poly. in rootof must be fraction free",0,"Polynome minimal de rootof ne doit pas contenir de fraction"},
{"Minus",0,"minus"},
{"Modgcd: no suitable evaluation point",0,"Modgcd: pas de point d'évaluation convenable"},
{"Modular factorization not yet accessible",0,"Factorisation modulaire pas encore implementée"},
{"Modulo too large",0,"Modulo trop grand"},
{"Multi-recurrences implemented only for 1 step",0,"Récurrences multiples implementées seulement pour 1 pas"},
{"Multivariate GF factorization not yet implemented",0,"Factorisation a plusieurs variables sur un corps fini non implementée"},
{"Multivariate finite field factorzation expects a unitary polynomial regular at 0. Try to translate with respect to one variable",0,"Factorisation sur un corps fini à plusieurs variables nécessite un polynôme unitaire régulier en 0. Essayez de translater par rapport à une variable"},
{"Near ",0,"Proche "},
{"Negative binomial: estimating n and p from data ",0,"Loi binomiale negative, estimation de n et p par les donnees"},
{"Negative polynome power",0,"Puissance négative de polynôme"},
{"Negative second Dirac argument",0,"Deuxieme argument de Dirac negatif"},
{"Negative value encoutered",0,"Valeur négative rencontrée"},
{"No case applies",0,"Aucun cas ne s'applique"},
{"No check were made for singular points of antiderivative ",0,"Il n'y a pas eu de test pour les points singuliers de la primitive"},
{"No help file found",0,"Pas de fichier d'aide"},
{"No irreducible primitive polynomial found",0,"Pas de polynome primitif irréductible trouvé"},
{"No mathml support",0,"Pas de support mathml disponible"},
{"No solution found by bisection. Trying iterative method starting at 0",0,"Pas de solution trouvee par dichotomie. On essaie une methode iteratibve en demarrant de 0"},
{"No solution in ring",0,"Pas de solution dans l'anneau"},
{"No such user ",0,"Utilisateur inconnu "},
{"Non assigned variable",0,"Variable non assignée"},
{"Non existent Folder",0,"Répertoire introuvable"},
{"Non holomorphic function ",0,"Fonction non holomorphe "},
{"Non integer argument",0,"Argument non entier"},
{"Non integer values for adequation to a discrete distribution",0,"Valeurs non entieres pour adequation a une distribution discrete"},
{"Non linear equations",0,"Équation non linéaire"},
{"Non positive definite",0,"N'est pas définie positive"},
{"Non regular value ",0,"Valeur non reguliere"},
{"Non-empty folder",0,"Répertoire non vide"},
{"Normal density, estimating mean and stddev from data ",0,"Densite normale, estimation de la moyenne et de l'ecart-type par les donnees"},
{"Normal density, estimating mean from data ",0,"Densite normale, estimation de la moyenne par les donnees"},
{"Normal density, estimating std deviation from data ",0,"Densite normale, estimation de l'ecart-type par les donnees"},
{"Not a TI89/92 program/function/group file",0,"N'est pas un fichier programme/fonction/group TI89/92"},
{"Not a line!",0,"N'est pas une droite!"},
{"Not a potential",0,"N'est pas un potentiel"},
{"Not a power of a prime",0,"N'est pas une puissance d'un nombre premier"},
{"Not a vector potential",0,"N'est pas un potentiel vecteur"},
{"Not bindable",0,0},
{"Not enough degree of freedom with default values. Add classes,classmin,classsize parameters",0,"Pas assez de degres de liberte pour les valeurs par defaut. Ajoutez les parametres classes,classmin,classsize."},
{"Not expandable ",0,"Non développable "},
{"Not implemented or bad argument type/value",0,"Non implemente ou mauvais type/valeur d'argument"},
{"Not implemented, e.g. for multivariate mod/approx polynomials",0,"Non implementé (par ex pour des polynômes modulaires ou approches de dim>1)"},
{"Not implemented, please recompile giac with PARI",0,"Pas implémenté, recompilez giac avec PARI"},
{"Not invertible",0,"Non inversible"},
{"Not invertible matrice",0,"Matrice non inversible"},
{"Not irreducible or not primitive polynomial",0,"Polynôme non irreductible ou non primitif"},
{"Not linked with GSL",0,"Librairie GSL indisponible"},
{"Not long enough",0,"Pas assez long"},
{"Not yet implemented",0,"A implementer"},
{"Now e.g. ",0,"Par exemple "},
{"Null polynomial",0,"Polynôme vide/nul"},
{"Number of primes ",0,"Nombre de premiers "},
{"Odd function %gen, even function %gen. Reflection Oy",0,"Fonction impaire %gen, fonction paire %gen. Symetrie Oy"},
{"Odd function %gen. Center O",0,"Fonction impaire %gen. Symetrie centrale en O"},
{"Odd functions. Center O",0,"Fonctions impaires. Symetrie centrale O."},
{"Operator name must be of type string",0,0},
{"Option keep_pivot not applicable",0,"Option keep_pivot non appliquable"},
{"Or condition not implemented",0,"Condition 'ou' non implémentée"},
{"Order of derivation must be positive",0,"Ordre de dérivation doit être positif"},
{"Overflow",0,"Dépassement"},
{"PARI locked by another thread. Try again later.\nIf PARI is locked by a cancelled thread, you can unlock it with pari_unlock()",0,"PARI est occupé sur une autre tâche. Essayez plus tard\nSi PARI est bloqué par une  tâche annulée, vous pouvez le débloquer avec pari_unlock()"},
{"Parabolic asymptote direction %gen at infinity",0,"Branche parabolique de direction %gen en l'infini"},
{"Parabolic asymptote direction at %gen: %gen",0,"Branche parabolique en %gen de direction %gen"},
{"Paraboloid cylinder",0,"Cylindre parabolique"},
{"Parallel lines",0,0},
{"Parallel plans",0,"Plans parallèles"},
{"Parent insmod",0,0},
{"Parser internal token",0,"Token interne"},
{"Partial fraction %gen -> Hermite reduction -> integrate squarefree part %gen",0,"Decomposition en elements simples %gen -> reduction de Hermite -> integration de la partie sans racines multiples %gen"},
{"Partial fraction integration of %gen",0,"Integrale par decomposition en elements simples de %gen "},
{"Perhaps you meant ",0,"Vous voulez dire peut être "},
{"Periodic function T=%gen",0,"Fonction periodique T=%gen "},
{"Piecewise definite integration: can only handle linear < or > condition",0,"Intégration définie avec piecewise: ne peut traiter que des inéquations linéaires"},
{"Pinstant=",0,"Pinstant="},
{"Please try xcas on Linux or an Unix",0,"Essayer xcas avec Linux ou Unix"},
{"Please use +infinity or -infinity since infinity is unsigned",0,"Utiliser +infinity or -infinity car infinity n'a pas de signe"},
{"Plotfunc 2nd arg must be var or [var1,var2]",0,"2eme argument de plotfunc doit être une variable ou [var1,var2]"},
{"Plotfunc: Range must be [xmin,ymin] or [xmax,ymax]",0,"Plotfunc: l'intervalle doit être [xmin,ymin] ou [xmax,ymax]"},
{"Plotfunc: bad range value!",0,"Plotfunc: intervalle incorrect!"},
{"Plotfunc: bad variable name",0,"Plotfunc: nom de variable incorrect"},
{"Plotfunc: unable to discretize: xmin, xmax, step=",0,"Plotfunc: impossible de discrétiser: xmin, xmax,step="},
{"Plotparam: unable to discretize: tmin, tmax, tstep=",0,"Plotparam: impossible de discrétiser: tmin, tmax, tstep="},
{"Point is not on curve",0,"Le point n'est pas sur la courbe"},
{"Poisson distribution, estimating parameter from data mean ",0,"Distribution de Poisson, estimation du parametre par la moyenne des donnees"},
{"Polynomial exponent overflow.",0,0},
{"Polynomials a,b in use: #a ",0,"Polynômes a,b utilisés: #a "},
{"Powered by Giac 1.1.3, B. Parisse and R. De Graeve, Institut Fourier, Universite Grenoble I, France",0,0},
{"Primitive of %gen is polynomial of same degree*same exponential %gen",0,"La primitive de %gen est un polynome de meme degree*la memem exponentielle %gen"},
{"Probabilistic algorithm for determinant\n(run proba_epsilon:=0 for a deterministic answer, this is slower).\nError probability is less than ",0,"Algorithme probabiliste pour le calcul du determinant\n(la commande proba_epsilon:=0 force l'utilisation d'un algorithme deterministe plus lent)\nLa probabilite d'erreur est inferieure a "},
{"Probabilistic answer. Run proba_epsilon:=0 for a certified result. Error <",0,"Reponse non deterministe. Utilisez proba_epsilon:=0 pour une reponse certifiee. Erreur <"},
{"Probably not a Riemann sum",0,"Probablement pas une somme de Riemann"},
{"Proc Parameters",0,"Paramètres de procédure"},
{"Program killed",0,"Programme interrompu"},
{"Proot error : no root found for ",0,"Erreur dans proot: aucune racine trouvée pour "},
{"Psi/Zeta/Eta: bad second argument",0,"Psi/Zeta/Eta: second argument incorrect"},
{"Quadratic sieve failure, perhaps number too large",0,"Quadratic sieve failure, perhaps number too large"},
{"Quaternion has 1 or 4 arguments",0,"Quaternion a 1 ou 4 arguments"},
{"RK8 evolve not successfull",0,"Echec de résolution par RK8"},
{"Reserved word:",0,"Mot-clef réservé"},
{"Restoring epsilon to 1e-6 from ",0,"Fixe epsilon a 1e-6 au lieu de "},
{"Restoring proba epsilon to 1e-6 from ",0,"Fixe proba epsilon a 1e-6 au lieu de "},
{"Returning estimated Pcumul, Pinstant, Ptotal, Pinstantmax, tmax, R",0,"Renvoie l'estimation de Pcumul, Pinstant, Ptotal, Pinstantmax, tmax, R"},
{"Risch diff dimension",0,0},
{"Run convert(matrix,array) for dense conversion",0,"Tapez convert(matrix,array) pour avoir une matrice dense"},
{"Running TI89 text translation __.ti",0,"Exécute la traduction TI89, fichier __.ti"},
{"Running a probabilistic check for the reconstructed Groebner basis. If successfull, error probability is less than ",0,"Execution d'une verification non deterministe pour la base de Groebner reconstruire. Si le test reussit, la probabilite d'avoir une reponse fausse est inferieure a "},
{"Running in secure mode",0,"Exécution en mode sécuré"},
{"Running maple text translation __.map",0,"Exécute la traduction Maple, fichier __.map"},
{"Running non recursive evaluator",0,"Exécution en mode d'évaluation non récursive"},
{"SVD is implemented for numeric matrices, running evalf first",0,"SVD est implemente pour des matrices approchees, on execute evalf avant"},
{"Sample adequation to ",0,"Adéquation d'un echantillon a "},
{"Sample adequation to a finite discrete probability distribution\nChi2 test result ",0,"Adequation d'un echantillon a une distribution discrete\nResultat du test du Chi2"},
{"Searching int of ",0,"Cherche intégrale de "},
{"Selecting last arc",0,"Sélection du dernier arc"},
{"Series internal bug",0,"Series : bug interne"},
{"Setting ",0,"Paramètres "},
{"Sieve error: Not enough memory ",0,"Sieve erreur: pas assez de mémoire "},
{"Sieve first prime ",0,"Sieve first prime "},
{"Sieve tolerance factor ",0,"Sieve tolerance factor "},
{"Sign error ",0,"Erreur de signe "},
{"Simplification assuming ",0,"Simplification en supposant "},
{"Singular parametric Sturm sequence ",0,"Suite de Sturm parametrique singuliere "},
{"Singular point %gen, point %gen direction %gen kind (%gen,%gen)\nTaylor expansions %gen",0,"Point singulier %gen, point %gen direction %gen genre (%gen,%gen)\nDeveloppements de Taylor %gen"},
{"Singular points directions: [cell_i, cell_j, singularity, next solution] ",0,"Point singuliers, directions:[no_cellule_horiz,no_cellule_vertical,singularite,vers la prochaine solution]"},
{"Solution may be wrong since a and b are not prime together: ",0,"La solution peut être fausse si a et b ne sont pas premiers entre eux"},
{"Solve with fractional power:",0,"Résoudre avec une puissance fractionnaire :"},
{"Solving by bisection with change of variable x=tan(t) and t=-1.57..1.57. Try fsolve(equation,x=guess) for iterative solver or fsolve(equation,x=xmin..xmax) for bisection.",0,"Recherche par dichotomie avec changement de variable x=tan(t) pour t=-1.57..1.57. Essayze fsolve(equation,x=guess) pour un methode iterative ou fsolve(equation,x=xmin..xmax) par dichotomie"},
{"Solving with initial guess 0. Try fsolve(equation,x=guess) for iterative solver or fsolve(equation,x=xmin..xmax) for bisection.",0,"Resolution iterative avec valeur initiale 0. Essayez fsolve(equation,x=guess) en iteratif ou fsolve(equation,x=xmin..xmax) par dichotomie."},
{"Some units could not be converted to MKSA",0,"Certaines unites n'ont pu etre convertie vers MKSA"},
{"Sorry! Debugging requires a true operating system",0,"Desolé! Pour débuguer il faut un système d'exploitation meilleur"},
{"Spreadsheet evaluation interrupted",0,"Evaluation du tableur interrompue"},
{"Spreadsheet matrix argument max size 4000 exceeded",0,"Les matrices du tableur ont une taille maximum de 4000"},
{"Square free factor mod bug",0,"Bug dans factorisation squarefree modulaire"},
{"Square is flat!",0,"Le carré est plat!"},
{"Stopped by user interruption",0,"Interrompu par l'utilisateur"},
{"Stopped by user interruption.",0,"Interrompu par l'utilisateur"},
{"Stopped in loop",0,"Arrete dans la boucle"},
{"Sum of coeff is 0",0,"La somme des coeffs est nulle"},
{"Summation variable must be != from series expansion variable",0,"Variable de sommation doit être différente de la variable de développement en séries"},
{"Symmetric asymptote %gen",0,"Asymptote par symétrie %gen"},
{"Symmetric horizontal asymptote %gen",0,"Asymptote horizontale par symetrie %gen"},
{"Symmetric vertical asymptote %gen",0,"Asymptote verticale par symetrie %gen"},
{"Syntax residue(expr,x=a)",0,"Syntaxe resiude(expr,x=a)"},
{"TI stop",0,"TI stop"},
{"Taylor abs with unsigned limit",0,"Taylor abs avec une limite sans signe"},
{"Taylor of ceil with unsigned limit",0,"Taylor de ceil avec une limite non signée"},
{"Taylor of floor with unsigned limit",0,"Taylor de floor avec une limite non signée"},
{"Taylor of round with unsigned limit",0,"Taylor de round avec une limite non signée"},
{"Taylor sign with unsigned limit",0,"Taylor: sign avec une limite sans signe"},
{"Temporary replacing surd/NTHROOT by fractional powers",0,"Remplacement temporaire de surd/NTHROOT par une puissance fractionnaire"},
{"Test returns 0 if probability to observe data is less than ",0,"Le test renvoie 0 si la probabilite d'observer les donnees est inferieure a "},
{"Test returns 1 otherwise (can not reject null hypothesis)",0,"Le test renvoie 1 sinon (on ne peut rejeter l'hypothese nulle)"},
{"The choice was done assuming ",0,"Le choix a ete fait en supposant "},
{"This function works only in radian mode",0,"Fonctionne seulement en mode radians"},
{"Thread ",0,"Tâche "},
{"Time",0,"Temps"},
{"To be implemented",0,"A implementer"},
{"To get a point, run point(",0,"Pour obtenir un point, tapez point("},
{"To_int",0,0},
{"Too few arguments: ",0,"Pas assez d'arguments: "},
{"Too many arguments: ",0,"Trop d'arguments: "},
{"Too many recursion levels",0,"Trop de niveaux de récursions"},
{"Too many recursions",0,"Trop de récursions"},
{"Too many recursions)",0,"Trop de récursions)"},
{"Too many variables ",0,"Trop de variables "},
{"Too much substitution variables",0,"Trop de variables de substitution"},
{"Too short for a TI archive",0,"Trop court pour une archive TI"},
{"Try unidirectional series",0,"Essayez un développement en séries unidirectionnel"},
{"Try_catch must have 3 or 4 args",0,"Try_catch doit avoir 3 ou 4 args"},
{"Unable to build a single algebraic extension for simplifying.\nTrying rational simplification only. This might return a wrong answer if simplifying 0/0!",0,0},
{"Unable to cancel step at ",0,"Impossible d'éliminer le saut en "},
{"Unable to check sign ",0,"Impossible de déterminer le signe"},
{"Unable to check sign: ",0,"Impossible de déterminer le signe: "},
{"Unable to check test at x=",0,"Impossible de faire le test en x="},
{"Unable to compute gbasis with giac, perhaps dimension is too large",0,"Impossible de calculer la base de Groebner avec giac, peut-etre que la dimension est trop grande"},
{"Unable to convert CoCoA data",0,"Impossible de convertir une donnée CoCoA"},
{"Unable to convert sum to Euler Mac-Laurin ",0,0},
{"Unable to convert to euler mac laurin",0,"Impossible à convertir sous forme d'Euler Mac-Laurin"},
{"Unable to convert to float ",0,"Impossible de convertir en réel "},
{"Unable to convert to float (in sto) ",0,"Impossible de convertir en réel (dans sto) "},
{"Unable to convert to integer ",0,"Impossible de convertir en entier"},
{"Unable to convert to integer (in sto) ",0,"Impossible de convertir en entier (dans sto) "},
{"Unable to convert to vector ",0,"Impossible de convertir en vecteur "},
{"Unable to convert to vector (in sto) ",0,"Impossible de convertir en vecteur (dans sto) "},
{"Unable to convert user type to galois field",0,"Impossible de convertir un type user en galois_field"},
{"Unable to divide, perhaps due to rounding error",0,"Division euclidienne non exacte, peut-être des erreurs d'arrondis"},
{"Unable to eval test in loop : ",0,"Impossible d'évaluer le test dans la boucle : "},
{"Unable to factor ",0,"Impossible de factoriser"},
{"Unable to find a modulus to solve",0,"Impossible de trouver un mod pour solve"},
{"Unable to find a particular solution for inhomogeneous part",0,"Impossible de trouver une sol. particulière de la partie non homogène"},
{"Unable to find all eigenvalues",0,"Impossible de trouver toutes les valeurs propres"},
{"Unable to find common minimal polynomial",0,"Impossible de trouver un polynôme minimal commun"},
{"Unable to find convexity",0,"Impossible de determiner la convexite"},
{"Unable to find critical points",0,"Impossible de trouver les points critiques"},
{"Unable to find exact eigenvalues. Trying approx",0,"Impossible de trouver toutes les valeurs propres exactes. On essaie en approche."},
{"Unable to find inflection points",0,"Impossible de trouver les points d'inflexion"},
{"Unable to find numeric integral using Romberg method, returning the last approximations",0,"Impossible de touver l'intégrale numérique avec Romberg, on renvoie la dernière approximation"},
{"Unable to find numeric values solving equation. For trigonometric equations this may be solved using assumptions, e.g. assume(x>-pi && x<pi)",0,"Impossible de trouver des valeurs numeriques solutions de l'equation. Pour des inequations trigonometriques, vous pouvez essayer de faire des hypotheses, comme supposons(x>=pi && x<pi)"},
{"Unable to find pic_var_tag length",0,"Impossible de trouver la longueur de pic_var_tag"},
{"Unable to find singular points",0,"Ne peut trouver les points singuliers"},
{"Unable to find singular points of antiderivative",0,"Ne peut trouver les points singuliers de la primitive"},
{"Unable to find text_var_tag length",0,"Impossible de trouver la longueur de text_var_tag"},
{"Unable to guess sigma using data",0,"Impossible d'estimer l'ecart-type"},
{"Unable to handle ",0,"Impossible de gérer "},
{"Unable to handle approx. or algebraic extension singular point ",0,"Impossible de gérer des points singuliers approchés ou extensions algébriques"},
{"Unable to handle coeff of homogeneous part",0,"Impossible de trouver le coefficient de la partie homogène "},
{"Unable to handle this kind of recurrence",0,"Type de récurrence non implementée"},
{"Unable to handle type [sym2poly.cc]",0,"Impossible de gérer le type [sym2poly.cc]"},
{"Unable to handle when condition ",0,"Impossible de traiter la condition when "},
{"Unable to isolate ",0,"Impossible d'isoler "},
{"Unable to isolate function ",0,"Impossible d'isoler la fonction"},
{"Unable to make thread",0,"Impossible de lancer une tâche"},
{"Unable to minimize at given precision, last value ",0,"Impossible de minimiser la dernière valeur à la précision donnée "},
{"Unable to open ",0,"Impossible d'ouvrir"},
{"Unable to open file ","Unable to open file ","Impossible d'ouvrir le fichier "},
{"Unable to open file or unable to code data",0,"Impossible d'ouvrir le fichier ou de coder les données"},
{"Unable to read file",0,"Impossible de lire le fichier "},
{"Unable to register ",0,"Impossible d'enregistrer "},
{"Unable to solve",0,"Impossible de résoudre"},
{"Unable to solve differential equation",0,"Impossible de résoudre l'equation differentielle"},
{"Unable to solve inequations with approx coeffs ",0,"Impossible de résoudre une inéquation a coeffs approchés"},
{"Unable to solve intersection equation ",0,"Impossible de résoudre l'équation donnant l'intersection "},
{"Unable to solve recurrence",0,"Impossible de résoudre la récurrence"},
{"Unable to sort ",0,"Impossible de trier "},
{"Unable to sort boundaries ",0,"Impossible de trier les bornes"},
{"Unable to sum ",0,"Impossible de faire la somme "},
{"Undef/Unsigned Inf encountered in limit",0,"Undef/infinity rencontré dans limit"},
{"Undefined integral",0,0},
{"Underflow",0,"Nombre trop petit"},
{"Uniform density, estimating interval boundaries from data ",0,"Densite uniforme, estimation de l'intervalle par les donnees"},
{"Union",0,"union"},
{"Unitialized local variable ",0,"Variable locale non initialisee "},
{"Unitialized parameter ",0,"Parametre non initialisee "},
{"Unknown instruction tag:",0,"Tag inconnu:"},
{"Unknown secondary tag",0,"Tag secondaire inconnu"},
{"Unknown subsop rule ",0,"subsop : règle inconnue "},
{"Unknown sysvar tag",0,"Tag sysvar inconnu"},
{"Unknown tag ",0,"Tag inconnu "},
{"Use pencolor for the turtle",0,"Utilisez pencolor pour la tortue"},
{"User operator not available on this architecture",0,"Opérateur utilisateur non disponible sur cette architecture"},
{"Using ",0,"En utilisant "},
{"Using multiplier ",0,"En utilisant multiplier "},
{"Using sound parameters: channels, rate, bits, records ",0,"Utilise les parametres pour le son: canaux, debit, bits, enregistrements "},
{"Values out of range",0,"Valeurs hors limite"},
{"Variable ",0,"Variable "},
{"Variable t should be purged",0,"Variable t doit être purgée"},
{"Variable u should be purged",0,"Variable u doit être purgée"},
{"Variable v should be purged",0,"Variable v doit être purgée"},
{"Variable x should be purged",0,"Variable x doit être purgée"},
{"Variable y should be purged",0,"Variable y doit être purgée"},
{"Variable z should be purged",0,"Variable z doit être purgée"},
{"Variables must be free",0,"Variable doit être purgée"},
{"Variations %gen\n%gen",0,0},
{"Variations (%gen,%gen)\n%gen",0,0},
{"Vector of 2 integer arguments expected",0,"Attend un vecteur de 2 entiers en argyment"},
{"Vertical asymptote %gen",0,"Asymptote verticale %gen"},
{"Vertical asymptote at %gen: %gen",0,"Asymptote verticale en %gen: %gen"},
{"Vertical parabolic asymptote at %gen",0,"Branche parabolique verticale en %gen"},
{"Warning ",0,"Attention "},
{"Warning : using implicit multiplication for (",0,"Attention : utilisation de multiplication implicite pour ("},
{"Warning disabled",0,"Attention, desactive"},
{"Warning enabled",0,"Attention, active"},
{"Warning time reversal",0,"Attention temps inversé"},
{"Warning! Algebraic extension not implemented yet for poly ",0,"Attention! Extension algébrique non implémentée pour les poly "},
{"Warning! Could not loop or reach boundaries ",0,"Attention! Impossible de finir la boucle ou d'atteindre les bornes "},
{"Warning! Leaving Gauss-Seidel iterative algorithm after maximal number of iterations. Check that your matrix is diagonal dominant.",0,0},
{"Warning! Leaving Jacobi iterative algorithm after maximal number of iterations. Check that your matrix is diagonal dominant.",0,0},
{"Warning! Leaving conjugate gradient algorithm after dimension of matrix iterations. Check that your matrix is hermitian/symmetric definite.",0,0},
{"Warning! Solving parametric inequation requires assumption on parameters otherwise solutions may be missed. The solutions of the equation are ",0,"Attention, resoudre des inequations parametriques necessite des hypotheses sur les parametres sinon des solutions peuvent manquer. Les solutions de l'equation sont "},
{"Warning, =< is in-place assign, check ",0,"Attention, =< est une affectation en place (par reference), vérifiez "},
{"Warning, Dirac function outside summation interval",0,"Attention, masse de Dirac en-dehors de l'intervalle de sommation"},
{"Warning, Ei(x,1) is defined as -Ei(-x), not as Ei(x)",0,"Attention, Ei(x,1) est défini comme -Ei(-x), pas comme Ei(x)"},
{"Warning, argument is not an equation, solving ",0,"Attention, l'argument n'est pas une équation, on résout "},
{"Warning, assuming derivative commutes with infinite sum",0,"Attention, on suppose que la derivee commute avec la somme infinie."},
{"Warning, checking for positivity of a root depending of parameters might return wrong sign: ",0,"Attention, la recherche du signe d'une racine dependant d'un parametre peut etre incorrecte"},
{"Warning, choosing root of ",0,"Attentio, on choisit la racine de "},
{"Warning, complex variables is set, this can lead to fairly complex answers. It is recommended to switch off complex variables in the settings or by complex_variables:=0; and declare individual variables to be complex by e.g. assume(a,complex).",0,"Attention, le flag variables complexes est a 1, ceci peut amener a des resultats tres compliques. Il est recommande de mettre ce flag a 0 dans la configuration ou par la commande complex_variables:=0 et de declarer individuellement des variables complexes par exemple par assume(a,complex)"},
{"Warning, defining a derivative function should be done with function_diff or unapply: ",0,"Attention, pour définir la fonction derivée utiliser fonction_derivee ou unapply: "},
{"Warning, exponential x coeff is positive ",0,"Attention, exponential x coeff est positive "},
{"Warning, infinity is unsigned, perhaps you meant +infinity",0,"Attention, infinity n'a pas de signe, essayez peut-être +infinity"},
{"Warning, integration of abs or sign assumes constant sign by intervals (correct if the argument is real):\nCheck ",0,"Attention, l'integration de abs() ou sign() suppose un signe constant par intervalles (verifie si l'argument est reel):\n Verifiez "},
{"Warning, minimal polynomial is only irreducible, not necessarily primitive",0,"Attention, le polynome minimal est irreductible mais pas necessairement primitif"},
{"Warning, need to choose a branch for the root of a polynomial with parameters. This might be wrong.",0,"Attention, on choisit une branche pour la racine d'un polynome avec parametres. Cela pourrait etre faux."},
{"Warning, random search for irreducible polynomial did not work, starting exhaustive search",0,"Attention, la recherche aleatoire d'un polynome irreductible a echoue. On lance une recherche exhaustive."},
{"Warning, replacing ",0,"Attention, remplacement de "},
{"Warning, solutions were not checked!",0,"Attention, les solutions ne sont pas contrôlées !"},
{"Warning, the test a==b is performed by checking\nthat the internal representation of ",0,"Attention, le test a==b est effectue en testant que les representations internes de "},
{"Warning, trying to solve ",0,"Attention, essai de résolution"},
{"Warning, using x or y as variable in parametric plot may lead to confusion!",0,"Attention, utiliser x ou y comme variable dans une courbe parametrique est source d'ambiguite!"},
{"Warning, z*argument has a non-zero integral part",0,"Attention, z*argument a une partie entiere non nulle"},
{"Warning: ",0,"Attention: "},
{"Warning: Local variables shadow function arguments ",0,"Attention: des variables locales ont le meme nom que des arguments de la fonction "},
{"Warning: algebraic function defined in term of others functions may lead to evaluation errors",0,"Warning, une fonction algébrique définie par d'autres fonctions peut conduire à des erreurs d'évaluation"},
{"Warning: algsubs selected one branch",0,"Attention, algsubs sélectionne une branche"},
{"Warning: multivariate GF factorization is experimental and may fail",0,"La factorisation de polynomes a plusieurs variables sur un corps fini est experimentale"},
{"Warning: non-square matrix!",0,"Attention : n'est pas une matrice carree"},
{"Warning: not a graph matrix!",0,"Attention : n'est pas un graphe matriciel"},
{"Warning: piecewise indefinite integration does not return a continuous antiderivative",0,"Attention : la primitive calculee d'une fonction continue par morceaux n'est pas forcément continue"},
{"Warning: pole at ",0,"Attention: pôle en "},
{"Warning: sign reversal",0,"Attention, changement de signe"},
{"Warning: solving by reducing number of unknowns to number of equations: ",0,"Attention, on résout en réduisant le nbre d'inconnues au nbre d'équations: "},
{"Warning: solving in ",0,"Attention: resolution en "},
{"Warning: some commands like subs might change arguments order",0,"Attention: certaines commandes comme subs ont l'ordre des arguments inverse"},
{"Warning: svd is implemented for numeric matrices",0,"Attention : svd est implemente pour des matrices numeriques."},
{"Warning: unable to find ",0,"Attention, impossible de trouver "},
{"Warning: undefined",0,"Attention, non defini"},
{"Warning: vanishing non integral power expansion",0,"Attention: puissance non-entiere appliquee a un developpement en series qui s'annule"},
{"Warning: variable name ignored: ",0,"Attention: nom de variable ignore:"},
{"Wilcoxon statistic: ",0,"Statistique de Wilcoxon : "},
{"Wrong parameter type ",0,"Type de paramètre incorrect "},
{"[a % p, b % q,...]",0,"[a % p, b % q,...]"},
{"^200+1 will build an element of ",0,"^200+1 construira un élément de "},
{"a_root",0,"a_root"},
{"alg_ext.cc/common_EXT",0,0},
{"alg_ext.cc/ext_reduce",0,0},
{"alg_ext.cc/min_pol",0,0},
{"alg_ext.cc/polynome2vecteur",0,0},
{"algebraic_argument",0,"argument_algébrique"},
{"angle",0,"angle"},
{"angle plan with unknown",0,"angle plan avec inconnu"},
{"apply",0,"apply"},
{"apply_to_equal",0,"apply_to_equal"},
{"area(f(x),x=a..b,n,method])",0,"area(f(x),x=a..b,n,method])"},
{"asc",0,"asc"},
{"assert failure: ",0,"echec de l'assertion"},
{"at least 3 points by face",0,"au moins 3 points par face"},
{"bad pow ",0,"pow incorrect "},
{"bernoulli",0,"bernoulli"},
{"binop",0,"binop"},
{"calculation size limit exceeded",0,"taille limite de calcul dépassée"},
{"check_binary",0,"check_binary"},
{"check_type must have 2 args",0,"check_type doit avoir 2 args"},
{"checking gcd",0,"vérifier gcd"},
{"circle","circle","cercle"},
{"complex constructor",0,"constructeur complexe"},
{"complex<double>",0,"complexe<double>"},
{"complex_smod",0,"complex_smod"},
{"conj_harmonique",0,"conj_harmonique"},
{"content1mod",0,0},
{"cross",0,"cross"},
{"derive.cc/derive",0,0},
{"derive.cc/derive_SYMB",0,0},
{"desolve.cc/invztrans",0,0},
{"desolve.cc/pf_ilaplace",0,0},
{"diff of incomplete gamma with respect to non constant 1st arg not implemented",0,"derivee de la fonction gamma incomplete par rapport a un 1er argument non constant non implementee"},
{"diff of sum with boundaries or mute variable depending on differentiation variable",0,"derivee d'une somme dont les bornes ou la variable de sommation dependent de la variable de differentiation"},
{"dotvecteur",0,"dotvecteur"},
{"dotvector",0,"dotvector"},
{"empty local declaration",0,"Déclaration locale vide"},
{"enveloppe",0,"enveloppe"},
{"error",0,"erreur"},
{"error, odd exponent for prime ",0,"erreur, exposant impair pour les premiers "},
{"ext_reduce",0,"ext_reduce"},
{"ezgcd.cc/reduce_divrem2",0,0},
{"f(t)!=0:",0,"f(t)!=0:"},
{"fig_tag",0,"fig_tag"},
{"fminmax, range ",0,"fminmax, range "},
{"from_increment",0,"from_increment"},
{"fsolve([equations],[variables],[guesses])",0,0},
{"function_of",0,"function_of"},
{"galois field inv",0,"galois field inv"},
{"galois_field has 1 or 4 arguments (charac p, irred poly P, var name x, value as a poly of x or as a vector)",0,"galois_filed a 1 ou 4 arguments (caracteristique p, poly irred P, nom var x, valeur comne un polynôme en x ou un vecteur)"},
{"gausspol.cc/contentgcdmod",0,0},
{"gausspol.cc/cyclotomic",0,0},
{"gausspol.cc/divremmod2",0,0},
{"gausspol.cc/gcdheu",0,0},
{"gausspol.cc/mod_factor",0,0},
{"gausspol.cc/pow",0,0},
{"gen.cc/_FRAC2_SYMB",0,"gen.cc/_FRAC2_SYMB"},
{"gen2complex",0,"gen2complex"},
{"graham_sort_function",0,"fonction de tri de graham"},
{"hyperplan2hypersurface",0,"hyperplan2hypersurface"},
{"hyperplan_normal",0,"hyperplan_normal"},
{"hypersphere2hypersurface",0,"hypersphere2hypersurface"},
{"hypersphere_equation",0,"hypersphere_equation"},
{"hypersphere_parameq",0,"hypersphere_parameq"},
{"i=sqrt(-1), please use a valid identifier name",0,"i=sqrt(-1), utilisez un autre nom de variable"},
{"ichinrem2 1",0,"ichinrem2 1"},
{"ichinrem2 2",0,"ichinrem2 2"},
{"ichinrem2 3",0,"ichinrem2 3"},
{"ichinrem2 4",0,"ichinrem2 4"},
{"idn",0,"idn"},
{"ifactor.cc/ifactors",0,0},
{"ifactors",0,"ifactors"},
{"igamma: bad arg number",0,"igamma: nombre d'arguments incorrect"},
{"in integrate_rational",0,0},
{"in intgab_rational",0,0},
{"in linear_apply",0,0},
{"in linear_apply 2",0,0},
{"index.cc index_lcm",0,0},
{"index.cc index_m i_lex_is_greater",0,0},
{"index.cc index_m i_total_revlex_is_greater",0,0},
{"index.cc index_m operator +",0,0},
{"index.cc index_m operator -",0,0},
{"index.cc index_m operator >=",0,0},
{"index.cc operator +",0,0},
{"index.cc operator -",0,0},
{"index.cc operator /",0,0},
{"index.cc operator <=",0,0},
{"index.cc operator >=",0,0},
{"index.cc operator |",0,0},
{"inputform may be used in a window environment only",0,"inputform ne peut être utilisé que dans un environnement graphique"},
{"integrate begin",0,"intégration début"},
{"integrate id_rem ",0,0},
{"integrate step -2 ",0,0},
{"integrate step 0 ",0,"intégration pas 0 "},
{"integrate step 1 ",0,"intégration pas 1 "},
{"integrate step 2 ",0,"intégration pas 2 "},
{"integrate step 3 ",0,"intégration pas 3 "},
{"interp_tk",0,"interp_tk"},
{"interval",0,"intervalle"},
{"inv_EXT",0,"inv_EXT"},
{"invalid |",0,"| incorrect"},
{"invmodext",0,0},
{"line2curve",0,"line2curve"},
{"ln of unsigned or minus infinity",0,"ln de infinity non signe ou de -infinity"},
{"mac_tag",0,"mac_tag"},
{"makegen of type ",0,"makegen de type "},
{"makemat",0,"makemat"},
{"matrice_extract",0,"matrice_extract"},
{"mergematrice",0,"mergematrice"},
{"midpoint",0,"milieu"},
{"milieu",0,"milieu"},
{"minor_det option applies only to det",0,"Option minor_det s'applique seulement pour det"},
{"mmultck",0,"mmultck"},
{"modpoly.cc/DivRem",0,0},
{"modpoly.cc/ininttype2ZZ",0,0},
{"modpoly.cc/modularize",0,0},
{"modpoly.cc/powmod",0,0},
{"modpoly.cc/x_to_xp",0,0},
{"moyal.cc/_moyal",0,0},
{"multiplier ",0,"multiplier "},
{"no taylor method for ",0,"pas de méthode de Taylor pour "},
{"non tractable function ",0," fonction non traitable "},
{"not implemented",0,"non implemente"},
{"peval_1",0,"peval_1"},
{"plot.cc/parameter2point",0,0},
{"plotarea(f(x),x=a..b[,n,method])",0,"graphe_aire(f(x),x=a..b[,n,method])"},
{"pointon",0,"pointon"},
{"polymat2mat",0,"polymat2mat"},
{"polymat2matpoly",0,"polymat2matpoly"},
{"pos2cell",0,"pos2cell"},
{"printasunit error",0,0},
{"prodsum",0,0},
{"prog.cc/leave",0,0},
{"pseudo_rat_ro_rat",0,"pseudo_rat_ro_rat"},
{"q is not quadratic",0,"q n'est pas une forme quadratique"},
{"qb and rb not prime together!",0,"qb et rb non premiers entre eux!"},
{"rat_jordan_block",0,"rat_jordan_block"},
{"reciprocation","reciprocation","polaire reciproque"},
{"relations ",0,"relations"},
{"risch.cc/hermite_reduce",0,0},
{"rootof",0,"rootof"},
{"schur row ",0,"schur row "},
{"simplify preserving ",0,"simplification en conservant "},
{"solve error while finding critical points",0,"erreur de solve lors de la recherche des points critiques"},
{"solve.cc/my_F",0,0},
{"solve.cc/my_FdF",0,0},
{"solve.cc/my_dF",0,0},
{"solve.cc/my_df",0,0},
{"solve.cc/my_f",0,0},
{"solve.cc/my_fdf",0,0},
{"sommet",0,"sommet"},
{"sqrt_noabs of ",0,"sqrt_noabs of "},
{"start tag",0,"demarrer tag"},
{"sto ",0,"sto "},
{"sym2poly.cc/addfirstrow",0,0},
{"sym2poly.cc/algebraic_argument",0,0},
{"sym2poly.cc/bool sym2r (const",0,0},
{"sym2poly.cc/ckdeg2_rootof",0,0},
{"sym2poly.cc/equalposmat",0,0},
{"sym2poly.cc/is_root_of_deg2",0,0},
{"sym2poly.cc/sym2rxroot",0,0},
{"sym2poly/r2sym(const gen & e,const index_m & i,const vecteur & l)",0,0},
{"trig_fraction",0,0},
{"unknown rational operator",0,"Operator rationnel inconnu"},
{"vecteur.cc vecteur2gsl_vector",0,0},
{"vecteur2turtle",0,"vecteur2turtle"},
{"vector<int> operator %",0,"vecteur<entier> opérateur %"},
{"vector<int> operator /",0,"vecteur<entier> opérateur /"},
{"vector<int> operator >",0,"vecteur<entier> opérateur >"},
{"∂(expression,variable=value)",0,"∂(expression,variable=valeur)"},
{"∫(expression,var,lower,upper)",0,"∫(expression,var,inf,sup)"}
};
const int aspen_giac_records=872;
